// Auto-generated types from Supabase (run: supabase gen types typescript --local > packages/database/src/types/index.ts)
// Placeholder until first migration is applied.
//
// IMPORTANT: Each table must have a `Relationships` array — required by supabase-js v2.x.
// When real types are generated by Supabase CLI, this file is fully replaced.

import type { UserRole, MemberStatus, AttendanceStatus, SessionType } from "../enums";

export type { UserRole, MemberStatus, AttendanceStatus, SessionType } from "../enums";

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          slug: string;
          name: string;
          business_type: string;
          city: string | null;
          phone: string | null;
          logo_url: string | null;
          terminology: Json;
          plan: string;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["tenants"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["tenants"]["Insert"]>;
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          tenant_id: string | null; // null until onboarding wizard completes
          role: UserRole;
          full_name: string | null;
          phone: string | null;
          email: string | null;
          created_at: string;
        };
        Insert: {
          id: string;              // must equal auth.users.id
          tenant_id?: string | null;
          role: UserRole;
          full_name?: string | null;
          phone?: string | null;
          email?: string | null;
        };
        Update: Partial<Omit<Database["public"]["Tables"]["profiles"]["Row"], "id" | "created_at">>;
        Relationships: [
          {
            foreignKeyName: "profiles_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          }
        ];
      };
      members: {
        Row: {
          id: string;
          tenant_id: string;
          profile_id: string | null;
          guardian_id: string | null;
          full_name: string;
          phone: string | null;
          email: string | null;
          date_of_birth: string | null;
          gender: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          status: MemberStatus;
          joined_at: string;
          notes: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["members"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["members"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "members_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "members_guardian_id_fkey";
            columns: ["guardian_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          }
        ];
      };
      sessions: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          session_type: SessionType;
          start_time: string;
          end_time: string;
          days: string[];
          instructor_id: string | null;
          max_capacity: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["sessions"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["sessions"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "sessions_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          }
        ];
      };
      attendance: {
        Row: {
          id: string;
          tenant_id: string;
          member_id: string;
          session_id: string;
          date: string;
          status: AttendanceStatus;
          marked_by: string | null;
          marked_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["attendance"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["attendance"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "attendance_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "attendance_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          }
        ];
      };
      payments: {
        Row: {
          id: string;
          tenant_id: string;
          member_id: string;
          amount: number;
          currency: string;
          status: string;
          razorpay_payment_id: string | null;
          recorded_by: string | null;
          paid_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["payments"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["payments"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "payments_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: UserRole;
      member_status: MemberStatus;
      attendance_status: AttendanceStatus;
      session_type: SessionType;
    };
    CompositeTypes: Record<string, never>;
  };
};
